### ISSUE TITLE
Add hot reloading / fast refresh support

### ISSUE THREAD

**Issue by divyanshu013** [Instawork/hyperview#114]
Currently there is no way to take advantage of hot reload / fast refresh.

With hot reloading only the tree which is changing should reload and rest of the app should maintain its state. When hot reloading is not feasible (component tree throws some error or network connectivity) it should fallback to fast refresh (full tree reload).

**Comment by adamstep** [comment]
What's needed to take advantage of hot reload? Can you explain what would need to change under the hood to support this? Hyperview screens already don't require the JS code to reload to update the screen.

**Comment by divyanshu013** [comment]
In order to take advantage of hot reloading (or fast refresh) we would have to add support for [Hot Module Replacement](https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html).

A HMR architecture in a nutshell looks like (from related article):

![hmr-architecture](https://user-images.githubusercontent.com/6682655/71340109-bb315900-257b-11ea-92ca-50314dd403e3.png)

Under the hood, we would need to add support for HMR (or Hot XML reloading) in dev mode for hyperview. This could look something like this:

1. A "watcher" service would listen for file changes to the concerned XML and notify the hyperview component linked to the XML.
2. Hyperview component reloads the XML
3. It diffs the new XML against old and only replaces the concerned parts maintaining application state.

By "maintaining application state" consider there was a `text-input` with some value that was filled by the user. Hot reloading the XML wouldn't destroy this value instead keeping it intact (only changes made to the XML would be reflected in the components). Similarly, if a section was hidden from a fired behavior, it would still be hidden when the changes from new XML are reflected (unless changes were made on the XML to the concerned section).

All of this is already available in the current React Native and JS ecosystem.

### Related

- [HMR in React Native](https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading.html)
- [Fast Refresh in React Native](https://facebook.github.io/react-native/docs/fast-refresh)
