### ISSUE TITLE
Add proper linting support

### ISSUE THREAD

**Issue by divyanshu013** [Instawork/hyperview#115]
Currently there is no linting support for HXML. This often leads to problematic issues which are hard to debug. For example, I once wasted quite a bit of time trying to debug scrolling on a `view` just to realize later that the attribute `scroll` was misspelled.

Some of the most basic features are:

- Proper attributes being passed to elements
- Using behaviors at the right place
- Attribute names mismatch
- Catch linting errors from another included XML (with `include`)
- A template variable being used outside of its scope. For example, a loop variable being used outside the loop fails silently. (This should fail atleast in dev mode)

**Comment by adamstep** [comment]
It's useful to separate out two categories of errors that you mention here:
- HXML syntax: proper attributes and elements in the XML structure.
- Django templating errors (undeclared variables, unclosed tags, etc)

It's outside of the scope of the Hyperview project to catch Django templating errors. Django does throw errors in debug mode for template syntax problems, and has some settings for [additional warnings](https://docs.djangoproject.com/en/3.0/ref/templates/api/#how-invalid-variables-are-handled). I think we can even add linters that run on commit to help with consistency and to catch a few issues.

For HXML structure, it's a good idea to support XSD on the client. It looks like there are some JS libraries that do XSD validation, so maybe it wouldn't be too hard to support it. @divyanshu013 any thoughts?

**Comment by divyanshu013** [comment]
Schema definition might be a good start though I don't think it's an ideal solution on its own. What I'd in mind was something similar to what's already present in the JS ecosystem (which drastically improves the DX):

1. Something similar to static typechecking (like Flow or TS). For example when you misspell a prop (or attribute):

<img width="878" alt="image" src="https://user-images.githubusercontent.com/6682655/71339184-c9ca4100-2578-11ea-9a1e-dc3abef3ca6e.png">

In case of a syntax error, it points **exactly** to the point of failure with what was expected and what was found

<img width="775" alt="image" src="https://user-images.githubusercontent.com/6682655/71339361-3cd3b780-2579-11ea-9222-aa0e43faf5cc.png">

2. Something that integrates well with editors like VS Code (insert your favorite editor) (plugin architecture)

3. Something that catches and surfaces syntax issues in the editor itself (plus a CLI tool so it can be integrated with CI)

Another issue that surfaces with schema definitions is they would have to be periodically synced between client and server code.

It also makes tricky when custom elements are being used or when properties / attributes change on client side code. In this case, older and newer clients would expect a different schema definitions.
