### ISSUE TITLE
Introduce a better way to pass JSON data

### ISSUE THREAD

**Issue by divyanshu013** [Instawork/hyperview#118]
Currently we've a very tedious way of sending JSON data which looks something like this:

```xml
<behavior
	...
	redux:extra="{&quot;payload&quot;:{&quot;params&quot;:{&quot;title&quot;:&quot;{% trans 'FAQ' %}&quot;,&quot;url&quot;:&quot;{% trans faq.answer_link %}&quot;},&quot;routeName&quot;:&quot;MODALS/WEB_VIEW_MODAL&quot;}}"
/>
```

I don't think this is readable. Currently we've to copy paste it into editor, replace characters and then replace everything back and paste it into the XML and hope it works.

**Comment by adamstep** [comment]
There was a proposal for this a while ago here: https://instawork.atlassian.net/wiki/spaces/EN/pages/739017020/Proposal+Improved+syntax+for+Amplitude+Redux+behaviors

It shouldn't be too hard to implement as an enhancement, @divyanshu013 do you want to work on it?

**Comment by divyanshu013** [comment]
Currently I don't have spare time to look into this, can take a look later sometime unless someone else wants to pick it up.
