### ISSUE TITLE
Fix errors from temporarily disabled eslint rules

### ISSUE THREAD

**Issue by DanielSchaffer** [Instawork/hyperview#126]
Several rules from `eslint-plugin-hyperview` were disabled when upgrading the plugin in #125 

Re-enable the following rules in `.eslintrc` and fix the errors:

- [ ] `import/no-cycle`
- [ ] `lines-between-class-members`
- [ ] `no-else-return`
- [ ] `no-restricted-globals`
- [ ] `prefer-destructuring`
- [ ] `react/destructuring-assignment`
- [ ] `react/jsx-sort-props`
- [ ] `react/no-access-state-in-setstate`
- [ ] `sort-keys`

**Comment by flochtililoch** [comment]
Resolved in #215
