### ISSUE TITLE
How does serverside render these xml?

### ISSUE THREAD

**Issue by liuyang25** [Instawork/hyperview#197]
I see your examples are all static files. The data to show in the pages will need query from db in server side and refer to the user's permissions.  but how should I place these data into the xml which need to return to the client? Is there a reactlike lib for generate the page?

**Comment by adamstep** [comment]
Hi, 

You can use any server framework you want to render the XML response dynamically. If you're familiar with JS, you could use Express.js with a template framework like [Ejs](https://www.npmjs.com/package/ejs).

At Instawork, we use the [Django framework](https://www.djangoproject.com/) (in Python) and use the standard Django templating library to render the XML response.

It's also possible to use a static site generator like Jekyll or Hugo to render the XML pages at build-time, and host your app on a service like Netlify! This could be a good option if your app is read-only and doesn't write to the database.
