### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by matdrapeau** [Instawork/hyperview#203]
Would you have a complete example in order to provide authentication to an app by using username/password?
Would it be possible to use Bearer Authentication by passing a token in every request to the backend?

**Comment by adamstep** [comment]
Hi @matdrapeau , I don't have an example in the repo, but I can explain how this would be done.

Check out the demo app here: https://github.com/Instawork/hyperview/blob/a549a1b1f5660706cc4e4f8a26dc232bc580fc07/demo/screens/HyperviewScreen.js#L55

Note that all HTTP requests made in the Hyperview library go through a fetch wrapper where you can customize the request with params and headers. In this example app, we're adding headers to prevent caching for demo purposes. But in your app, you could add an `Authentication` header with a bearer token to make sure each request is authenticated against the backend. We do this in the Instawork application.

**Comment by matdrapeau** [comment]
@adamstep thanks for the input.
But in order to capture the token in a login response (using a login page) and reuse it in further requests, I don't know how and where it should happen. Also this bearer should be kept in cache for subsequent requests until it expires.
Can you provide a snippet of that part from Instawork application?
Thanks

**Comment by adamstep** [comment]
@matdrapeau there are two approaches that can work:

- Hyperview uses the iOS and Android networking stacks. These system libraries handle storing cookies. So if you make an authentication request that responds with the `Set-Cookie` header, then that cookie should be sent on subsequent requests to your backend.
- In the `fetchWrapper` code that I linked to above, you could detect and extract the Bearer token from your authentication request and store it using RN's [AsyncStorage](https://reactnative.dev/docs/asyncstorage). Then, on subsequent requests, you can read the token and add it to the request headers.

In the Instawork app, we use the second option of reading/writing the bearer token to local storage, and adding it to the request headers.
