### ISSUE TITLE
Any suggestions about we use hyperview to implement the whole app

### ISSUE THREAD

**Issue by blue3xp** [Instawork/hyperview#207]
Hi, I want to use the hyperview to implement the whole app, and use jsp or asp to bind data into the hxml. Could you give me some suggestions?

**Comment by adamstep** [comment]
Hi @blue3xp, I'm not familiar with JSP and ASP, but I can give some pointers on building the app.

The best place to start is the [demo app](https://github.com/Instawork/hyperview/tree/master/demo) in this repo. This is an Expo app set up with Hyperview. The only thing you'd need to change is to point the entrypoint URL of the demo app to your server: https://github.com/Instawork/hyperview/blob/master/demo/navigation/AppNavigator.js#L43 Then, when the app starts up, it will load the first screen from this URL, and you can open other screens or modals from there.

On the server side, like I said I'm not familiar with JSP or ASP. But if you can create a web server that responds with `Content-Type: application/xml` and the content is XML, then you can render it in the demo app. Hope that helps!
