### ISSUE TITLE
How to use SafeAreaView for hyperview

### ISSUE THREAD

**Issue by cengit** [Instawork/hyperview#212]
The purpose of SafeAreaView is to render content within the safe area boundaries of a device, so in my code I just wrap Hyperview with the SafeAreaView component.

**actual result:**
the first page in Hyperview is good, it display all content in the safe area, but when navigate to next hyperview page, the SafeAreaView is not working

**expected result:**
content expected to render in the safe area for all page

 what should I do to make it work for all page?

in the demo it just set the Header height=72, I think this is not a best practices, so any solutions for this? thanks

```
<style id="Header"
             alignItems="center"
             backgroundColor="white"
             borderBottomColor="#eee"
             borderBottomWidth="1"
             flexDirection="row"
             height="72"
             paddingLeft="24"
             paddingRight="24"
             paddingTop="24" />
```

this is what I do for my code

```
import { SafeAreaView } from 'react-native-safe-area-view';

export default function MyAwesomeApp() {
  return (
    <SafeAreaView style={{ flex: 1 }}>
      <Hyperview
        entrypointUrl={url}
        fetch={fetch}
        back={this.back}
        closeModal={this.closeModal}
        openModal={this.openModal}
        navigate={this.navigate}
        push={this.push}
      />
    </SafeAreaView>
  );
}
```

**Comment by cengit** [comment]
please see my screenshot as below.
first page: the header renders good, it renders in the safe area
<img width="452" alt="first-page" src="https://user-images.githubusercontent.com/3691806/103393143-3b5da780-4b5c-11eb-9a47-c6002283551e.png">

**second page: the header DID NOT renders in the safe area**
<img width="454" alt="second-page" src="https://user-images.githubusercontent.com/3691806/103393150-40baf200-4b5c-11eb-948b-ab1d264db15c.png">

**Comment by adamstep** [comment]
Hi @cengit , sorry for the delay in response. One question: are you basing your example on the demo code in the Hyperview repo? Just want to understand which version of react-navigation you're using.

**Comment by cengit** [comment]
@adamstep it's an old project, no on the demo code, we using "react-navigation": "2.18.0",

**Comment by adamstep** [comment]
@cengit thanks for the info. I looked into the issue over the weekend. Unfortunately, there's no supported way to get a safe area view in the current version of Hyperview. In our own apps, we use header height like you saw in the demo. Of course, this is not ideal because different phones will need different heights.

I think we can support this feature in Hyperview by adding an attribute to the `<screen>` tag. Maybe something like
```xml
<screen display-mode="safe-area">
  <!-- normal -->
</screen>
```

@flochtililoch what do you think?

**Comment by flochtililoch** [comment]
I'm not sure if there's anything in the SafeAreaView spec constraining it's use to the top level view only, so we might want to support this it at the view level. We might also want to use a boolean attributes to stay consistent with our existing "scroll" attribute which effectively swap the regular `<View>` component with a `<ScrollView>`, i.e.

```xml
<view safe-area="true" ...
```

**Comment by adamstep** [comment]
From my understanding, `SafeAreaView` should be used at the top level only: https://reactnative.dev/docs/safeareaview#example

> To use, wrap your top level view with a SafeAreaView with a flex: 1 style applied to it. You may also want to use a background color that matches your application's design.

**Comment by flochtililoch** [comment]
I think the example is just for common usage, but in practice, one can nest the `<SafeAreaView>` under other views. This might be useful when we want to render content outside the safe area, while still enforcing other content to only render within the safe area
i.e.

```js
  <View style={{ position: 'relative' }}>
    <SafeAreaView>
      <Text>
        Velit voluptas et alias atque provident sapiente consequuntur deserunt. Dolorem et non error
        dolorem voluptate amet accusantium. Corporis rerum sed labore quae sed qui quis quasi. Illo
        pariatur sint qui. Quasi quaerat id molestias. Necessitatibus et ipsa quia asperiores
        laborum neque. Quisquam dolorem consequatur illum. Ut magni iusto explicabo blanditiis quasi
        laborum incidunt earum. Eius ut in rerum ipsam. Officiis dolores suscipit consequatur
        placeat commodi eum. Vel possimus placeat aut eos tempore saepe. Esse assumenda eum illo sed
        aut earum quia voluptatibus. Recusandae qui iusto corporis sed atque. Veniam et possimus
        praesentium. Cum molestiae non velit minus voluptatibus quos illo sed. Et omnis ut soluta
        qui inventore molestias. Dolores voluptatem perspiciatis exercitationem consectetur minus
        illum. Quos quaerat omnis aut eius eos dolores velit. Et quia vel ea unde eum repudiandae.
        Repellat et ab sed. Show LessLipsum{' '}
      </Text>
    </SafeAreaView>
    <View style={{ position: 'absolute', top: 0, backgroundColor: 'red' }}>
      <Text>Testing</Text>
    </View>
  </View>
);
```

yields:

<img width="553" alt="Screen Shot 2021-01-11 at 10 37 45 AM" src="https://user-images.githubusercontent.com/309515/104223861-0c1b2600-53f9-11eb-926a-144818f7c465.png">

**Comment by adamstep** [comment]
@flochtililoch makes sense. But in terms of implementation, I worry about the conflict between `scroll`, `avoid-keyboard`, and now `safe-area` attributes. We already have 4 possible components we use based on the state of scrolling and keyboard avoidance: https://github.com/Instawork/hyperview/blob/master/src/components/hv-view/index.js#L40-L62

Safe area doesn't compose well with these other two features, so the implementation would be tricky in the general case. Any ideas how to handle this?

**Comment by flochtililoch** [comment]
I think we could either have some logic that explicitly ignore `safe-area` when `scroll` and/or `avoid-keyboard` are present, along with a yellow box warning and a warning in the documentation, or we could handle it the same way it's done in the `hyper-ref` component, by wrapping the resulting view in a `SafeAreaView`.

**Comment by adamstep** [comment]
I think I prefer the warning approach. I'd like to avoid wrapping the view (like we do for HyperRef), because it causes weird styling bugs with flex layouts (HyperRef already has this problem).

**Comment by flochtililoch** [comment]
Agreed

**Comment by cengit** [comment]
thanks guys, looking forward to this new feature...

**Comment by adamstep** [comment]
Included in latest release!
