### ISSUE TITLE
how to include one common style for each hyperview page?

### ISSUE THREAD

**Issue by cengit** [Instawork/hyperview#223]
this is my situation:

- I have several pages sharing the same common style, see below code between **common style start** and **common style end** 
- now I have to copy and paste the common styles to all pages, so I can use the common style in the page.

I think this is not a good practice, my question is: how can I include one common style for each hyperview page？so every time when there are changes for the common-style, I only need to update it in one place.

something just like when we working on a web project, we just need to include a common.css for all page

`<link rel="stylesheet" type="text/css" href="css/common.css">`

```xml
<doc lang="en"
	xmlns="https://hyperview.org/hyperview"
	xmlns:th="http://www.thymeleaf.org">
	<screen>
		<body style="Body">
			<header style="Header">
				<text action="back" delay='300' href="#" style="Header__Back">
					<text style="Header__Title">Title</text>
				</text>
			</header>
			<view scroll="true">
				<view style="m-16">
					<view style="flex-center-wrap">
						<text style="18-bold gray4">test text</text>
						<view style="btn btn-medium btn-primary">
							<text style="btn-label btn-primary"> === medium === </text>
						</view>
					</view>
				</view>
			</body>
			<styles>
				<style id="Header" paddingLeft="21" paddingRight="20" paddingBottom="10" paddingTop="10" backgroundColor="white" borderColor="#eee" borderBottomWidth="1" flexDirection="row" justifyContent="space-between" alignItems="flex-end"/>
				<style id="Header__Back" color="black" fontSize="18" fontWeight="500" />
				<style id="Header__Title" color="black" fontSize="16" fontWeight="bold" />
				<style id="Body" flex="1" backgroundColor="#fff" />
				<!-- common style start -->
				<!-- margin -->
				<style id="m-0" margin="0" />
				<style id="m-4" margin="4" />
				<style id="m-8" margin="8" />
				<style id="m-12" margin="12" />
				<style id="m-16" margin="16" />
				<style id="m-t-0" marginTop="0" />
				<style id="m-t-4" marginTop="4" />
				<style id="m-t-8" marginTop="8" />
				<style id="m-t-12" marginTop="12" />
				<style id="m-t-16" marginTop="16" />
				<style id="m-t-24" marginTop="24" />
				<style id="m-b-0" marginBottom="0" />
				<style id="m-b-4" marginBottom="4" />
				<style id="m-b-8" marginBottom="8" />
				<style id="m-b-12" marginBottom="12" />
				<style id="m-b-16" marginBottom="16" />
				<style id="m-b-24" marginBottom="24" />
				<style id="gray1" color="#283542"/>
				<style id="gray2" color="#596980"/>
				<style id="gray3" color="#8F9EB2"/>
				<style id="gray4" color="#BCC2CC"/>
				<style id="gray5" color="#E1E3E6"/>
				<style id="gray6" color="#E8E9EB"/>
				<style id="gray7" color="#F3F3F5"/>
				<style id="bold" fontWeight="700"/>
				<style id="medium" fontWeight="500"/>
				<style id="regular" fontWeight="400"/>
				<!-- button -->
				<style id="btn" borderColor="#ED1B2E" backgroundColor="#fff" borderWidth="1" borderRadius="24" justifyContent="center" paddingLeft="24" paddingRight="24" />
				<style id="btn-large" height="48" marginBottom="12"/>
				<style id="btn-medium" height="44" marginBottom="12"/>
				<style id="btn-small" height="36" marginBottom="12"/>
				<style id="btn-primary" backgroundColor="#ED1B2E" color="#fff" />
				<style id="btn-label" color="#ED1B2E" textAlign="center" fontSize="16" fontWeight="500"/>
				<style id="btn-label-small" fontSize="14" fontWeight="400"/>
				<!-- common style end -->
			</styles>
		</screen>
	</doc>
```

**Comment by cengit** [comment]
by the way, we use java as a xml server.

one solution in my mind is: **make the common-style code snippet as a java string variable and figure out a way to put it into the xml**

any suggestions? thanks in advance

**Comment by adamstep** [comment]
Hi @cengit , good suggestion about being able to link to external style resources. We have thought about adding that feature, but it can make layout more complicated. With external stylesheet, we need to handle async rendering, errors in case the stylesheet resource can't be fetched, etc. That's why we decided to make all styles included in the main request.

> one solution in my mind is: **make the common-style code snippet as a java string variable and figure out a way to put it into the xml**

We use a very similar solution in Django using template includes. I'm not familiar with rendering Java in XML, but I am sure there's a way to include a snippet of XML when rendering the response. This solution makes it easy to avoid copy/pasting the styles like you described.

**Comment by cengit** [comment]
thanks for the reply @adamstep
