### ISSUE TITLE
[Feature] support 'focus' and 'blur' trigger event for text-field component

### ISSUE THREAD

**Issue by terryatgithub** [Instawork/hyperview#236]
Hi @adamstep, sorry to disrupt you. We wonder if there are any plan or proposal to support the below feature: 

**[Feature] add the following triggers to the 'text-field' and 'text-area' component:**
- focus
- blur

We found that in acutal work we often need to verify the correctness of the fields filled by the user, or  have some linkage effects between fields. These situations all require timely feedback to the uses.

According to my understanding, now the only way to achieve this function is to encapsulate the 'Form' component of React Native by 'custom elements ' feature. but this method will be very inflexible, because the entire page would be a react native component, instead of a hyperview page. 

In view of this, if hyperview can support 'focus' and 'blur' trigger for text-field component, there would be more flexibility to deal with the above cases.

Or would you have some other plans or suggestions on above requirements ?
Looking forward to reply, and thank you so much.

btw:  now I am trying to  implement it in my hyperview branch.

![image](https://user-images.githubusercontent.com/12246394/110450882-954f9000-80fe-11eb-99b9-fb6d83b6ff90.png)

**Comment by terryatgithub** [comment]
@adamstep

**Comment by adamstep** [comment]
Thanks @terryatgithub ! This is a great suggestion, our team was considering adding this behavior ourselves. I will review your PR.

**Comment by adamstep** [comment]
Feature available in `0.38.0`.
