### ISSUE TITLE
App Store approval + Rendering ?

### ISSUE THREAD

**Issue by redbar0n** [Instawork/hyperview#247]
How easy is it to get a Hyperview app approved in the iOS App Store?

Since, as I understand it, the content of the app which is rendered is entirely controlled over-the-wire at runtime, the App Store reviewers won't know that what they are reviewing might be entirely changed immediately afterwards?

Or does Hyperview bundle and ship the views within the pre-downloaded app? Then merely allow the server to control navigation and select which of the pre-bundled views/components that are shown? That would be in line with [Server-Driven Rendering](https://medium.com/airbnb-engineering/whats-next-for-mobile-at-airbnb-5e71618576ab), if I understand it correctly.

**Comment by adamstep** [comment]
Hi @redbar0n,

> How easy is it to get a Hyperview app approved in the iOS App Store?
> 
> Since, as I understand it, the content of the app which is rendered is entirely controlled over-the-wire at runtime, the App Store reviewers won't know that what they are reviewing might be entirely changed immediately afterwards?

We haven't had any issues with app store approvals. There are many commonly-used app technologies that allow changing the app at runtime, such as:
- a wrapper around a web app
- [Codepush](https://github.com/microsoft/react-native-code-push#how-does-it-work) (load the React Native code from a server)
- Feature flags controlled from a server

Apple's guidelines have evolved to account for the fact that apps are often updated over-the-wire. The common interpretation of Section [2.5.2](https://developer.apple.com/app-store/review/guidelines/#software-requirements) means that you can update your app, as long as you don't introduce huge changes. So fixing bugs and tweaking the features is ok, but swapping out the app for a completely different one would not be ok. Like you mentioned, this cannot be enforced at submission time, but Apple will pull the app based on user complaints.

> Or does Hyperview bundle and ship the views within the pre-downloaded app? Then merely allow the server to control navigation and select which of the pre-bundled views/components that are shown? That would be in line with [Server-Driven Rendering](https://medium.com/airbnb-engineering/whats-next-for-mobile-at-airbnb-5e71618576ab), if I understand it correctly.

No, Hyperview does not bundle and ship views with the app. As Hypermedia, the server response defines the UI layout and interactions available to the user (including navigation).

**Comment by redbar0n** [comment]
Thank you for a very informative and candid answer!🙏🏼
