### ISSUE TITLE
hyperscript

### ISSUE THREAD

**Issue by 1cg** [Instawork/hyperview#249]
Hi there, this isn't a real issue but I couldn't dig up a good way to get in touch with @adamstep otherwise.  I am the creator of intercooler.js (and now htmx) and I came down to SF a while ago to chat with y'all about it and to see your awesome port of the concept to mobile development w/ hyperview.

Adam mentioned that, like me, he had done some hypercard work, and I wanted to let him know that when I ported intercooler to htmx, I decided to pull the event attributes and somewhat hacky `ic-action` attribute out and create a new front end programming language that is based on HyperTalk:

https://hyperscript.org

I thought he might get a kick out of it.

**Comment by adamstep** [comment]
Hi @1cg , good to hear from you! I've been following htmx pretty closely (we use Intercooler heavily at Instawork), and I've played around with Hyperscript too!

Specifically, I've been playing around with how htmx + hyperscript + web components can be used to create web apps. [Shoelace](https://shoelace.style/) plays well with htmx and hyperscript. I've been meaning to write up a blog post about it, I'll get in touch over email when it's ready to go up.

**Comment by 1cg** [comment]
that is *fantastic to hear adam*, closing this out as spam :)

**Comment by karneaud** [comment]
I know this is late but...what is the status of and its potential of Shoelace + Hyperview + Expo ? I am also interested as I am familiar with htmx and want to jump in to build mobile apps

**Comment by karneaud** [comment]
@adamstep would the integration of shoelace be a simple matter of "extending" the showlace component making sure that any required hyperview class component properties/ methods are met?
