### ISSUE TITLE
Feature: introduce new actions include and include-inner 

### ISSUE THREAD

**Issue by terryatgithub** [Instawork/hyperview#270]
in order to implement some complicated UI like below two-layer cascading menu, it's found that current actions can not match this requirement. 

![image](https://user-images.githubusercontent.com/12246394/117808129-16f2a400-b28f-11eb-802a-c7949fb43ced.png)

> And below actions are needed in this case
- `include`
`include` means replace the target element with the `contents of source element`, instead of source element itself.
- `include-inner`
`include-inner` means replace the target element's children with `the contents of source element`. 

> The name and meaning of both new actions are referred from the [include syntax of Thymeleaf](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#difference-between-thinsert-and-threplace-and-thinclude).

I'm testing these new actions now, and want to hear your opinions before raising a PR.
the implement code is like below:

```javascript
// hyperview/src/services/behaviors/index.js
/**
 * Returns a new Document object where the given action was applied to the target element
 * with the new element.
 */
export const performUpdate = (
  action: UpdateAction,
  targetElement: Element,
  newElement: Element,
): Document => {
  if (action === ACTIONS.REPLACE) {
    const { parentNode } = targetElement;
    if (parentNode) {
      parentNode.replaceChild(newElement, targetElement);
      return shallowCloneToRoot((parentNode: any));
    }
  }

  if (action === ACTIONS.REPLACE_INNER) {
    let child: ?Node = targetElement.firstChild;
    // Remove the target's children
    while (child !== null && child !== undefined) {
      const nextChild: ?Node = child.nextSibling;
      targetElement.removeChild(child);
      child = nextChild;
    }
    targetElement.appendChild(newElement);
    return shallowCloneToRoot(targetElement);
  }

  // new action : include
  if (action === ACTIONS.INCLUDE) {
    const { parentNode } = targetElement;
    if (parentNode) {
      let child: ?Node = newElement.firstChild;
      // Insert the newElement's children
      while (child !== null && child !== undefined) {
        const nextChild: ?Node = child.nextSibling;
        parentNode.insertBefore(child, targetElement);
        child = nextChild;
      }
      parentNode.removeChild(targetElement);
      return shallowCloneToRoot((parentNode: any));
    }
  }

  // new action : include-inner
  if (action === ACTIONS.INCLUDE_INNER) {
    let child: ?Node = targetElement.firstChild;
    // Remove the target's children
    while (child !== null && child !== undefined) {
      const nextChild: ?Node = child.nextSibling;
      targetElement.removeChild(child);
      child = nextChild;
    }
    child = newElement.firstChild;
    // Append the newElement's children
    while (child !== null && child !== undefined) {
      const nextChild: ?Node = child.nextSibling;
      targetElement.appendChild(child);
      child = nextChild;
    }
    return shallowCloneToRoot(targetElement);
  }
 
 ...
};
```

**Comment by adamstep** [comment]
@terryatgithub I'm not sure I understand. How is `include` and `include-inner` different from `replace` and `replace-inner`? I believe those behaviors should support the [document fragment syntax](https://hyperview.org/docs/reference_behavior_attributes#document-fragments).

So you could do something like:
```xml
<view id="menu">
<text action="replace-inner" href="#general-submenu" target="submenu">General</text>
</view>

<view id="submenu" />

<view hide="true">
  <view id="general-submenu">
    <text>Drivers</text>
    <text>Engineer</text>
  </view>
</view>
```

Would that work? If not, please provide an example XML of what you hope to achieve. Thanks!

**Comment by terryatgithub** [comment]
```

<!--                    stage zone-->
                    <view hide="true" id="Occupation_Stage_Zone">
                        <select-single th:id="${parentTitle}" th:each="parentTitle : ${occupations.keySet()}" th:value="${childOccupation}" >
                            <option style="content-item" th:value="${child.getJobTitle()}" th:each="child : ${occupations.get(parentTitle)}" >
                                <behavior trigger="select" action="hide" target="occupationMask"/>
                                <behavior trigger="select" action="set-value" th:new-value="${child.getJobTitle()}" target="idOccupation"/>
                                <behavior trigger="select" action="include-inner" target="Occupation_Stage_Zone" href="#Occupation_Reset_Zone" />
                                <behavior trigger="select" action="include" th:target="${parentTitle}" href="#occupationContent" />
                                <!--                                <view th:with="selectedValue=${child.getJobTitle()},${parentOccupation}=${parentTitle}"/>-->
                                <text style="content-label" th:text="${child.getJobTitle()}"></text>
                            </option>
                        </select-single>
                    </view>
<!--                    reset zone-->
                    <view hide="true" id="Occupation_Reset_Zone">
                        <select-single th:id="${parentTitle}" th:each="parentTitle : ${occupations.keySet()}"  >
                            <option style="content-item" th:value="${child.getJobTitle()}" th:each="child : ${occupations.get(parentTitle)}" >
                                <behavior trigger="select" action="hide" target="occupationMask"/>
                                <behavior trigger="select" action="set-value" th:new-value="${child.getJobTitle()}" target="idOccupation"/>
                                <behavior trigger="select" action="include-inner" target="Occupation_Stage_Zone" href="#Occupation_Reset_Zone" />
                                <behavior trigger="select" action="include" th:target="${parentTitle}" href="#occupationContent" />
                                <!--                                <view th:with="selectedValue=${child.getJobTitle()},${parentOccupation}=${parentTitle}"/>-->
                                <text style="content-label" th:text="${child.getJobTitle()}"></text>
                            </option>
                        </select-single>
                    </view>
```

**Comment by terryatgithub** [comment]
> @terryatgithub I'm not sure I understand. How is `include` and `include-inner` different from `replace` and `replace-inner`? I believe those behaviors should support the [document fragment syntax](https://hyperview.org/docs/reference_behavior_attributes#document-fragments).
> 
> So you could do something like:
> 
> ```
> <view id="menu">
> <text action="replace-inner" href="#general-submenu" target="submenu">General</text>
> </view>
> 
> <view id="submenu" />
> 
> <view hide="true">
>   <view id="general-submenu">
>     <text>Drivers</text>
>     <text>Engineer</text>
>   </view>
> </view>
> ```
> 
> Would that work? If not, please provide an example XML of what you hope to achieve. Thanks!

that is: later when I want to redo the replace action above, it can work. because the id `submenu` has been replaced, and not exist any more.

**Comment by terryatgithub** [comment]
> @terryatgithub I'm not sure I understand. How is `include` and `include-inner` different from `replace` and `replace-inner`? I believe those behaviors should support the [document fragment syntax](https://hyperview.org/docs/reference_behavior_attributes#document-fragments).
> 
> So you could do something like:
> 
> ```
> <view id="menu">
> <text action="replace-inner" href="#general-submenu" target="submenu">General</text>
> </view>
> 
> <view id="submenu" />
> 
> <view hide="true">
>   <view id="general-submenu">
>     <text>Drivers</text>
>     <text>Engineer</text>
>   </view>
> </view>
> ```
> 
> Would that work? If not, please provide an example XML of what you hope to achieve. Thanks!

that is: later when I need to re-do the replace action above, it won't work. because there will be two fragment which id=`general-submenu`.

**Comment by terryatgithub** [comment]
Because of this wonderful realization in #309  by Adam, this issue is fiexd.
