### ISSUE TITLE
Add editable attribute for text-field

### ISSUE THREAD

**Issue by Jasonwei1106** [Instawork/hyperview#276]
![image](https://user-images.githubusercontent.com/37089057/118637151-0f3f7c00-b808-11eb-9121-3e46dba8e5d0.png) 
Hi, I need `editable` attribute for text-field in some cases. There wasn't any issue when I add it on ios, however, `editable` does not supported on android devices. So I raise an issue here.

**Comment by adamstep** [comment]
The feature is now available in version [0.38.4](https://github.com/Instawork/hyperview/releases/tag/v0.38.4)
