### ISSUE TITLE
Ios KeyboardScrollView will leave extra white space

### ISSUE THREAD

**Issue by Jasonwei1106** [Instawork/hyperview#302]
When I have a KeybordScrollView on ios device, it will cause a problem like this. When text-field is focused, keyboard shows up, and it will push the textfield up. But, when the text-field is blurred, it will leave an extra space above the text-field. It is obvious when I only have one text-field. Even if when I have multiple text-fields, and it won't show the motion to push element down, when I scroll the view up, the white space will be there. It cannot go back unless I click the text-field again. I will put a simple example below. 

    <doc xmlns="https://hyperview.org/hyperview">
      <screen>
        <styles>
          <style
            id="Header"
            alignItems="center"
            backgroundColor="white"
            borderBottomColor="#eee"
            borderBottomWidth="1"
            flexDirection="row"
            paddingLeft="24"
            paddingRight="24"
            paddingBottom="16"
          />
          <style
            id="Header__Back"
            color="blue"
            fontSize="16"
            fontWeight="600"
            paddingRight="16"
          />
          <style id="Header__Title" color="black" fontSize="24" fontWeight="600" />
          <style id="Body" backgroundColor="white" />
          <style
              id="input"
              borderBottomColor="#E1E1E1"
              borderBottomWidth="1"
              borderColor="#4E4D4D"
              flex="1"
              fontSize="16"
              fontWeight="normal"
              paddingBottom="8"
              paddingTop="8"
            >
            <style
              id="subtitle"
              margin="20"
              fontSize="16"
              fontWeight="bold"
              marginBottom="0"
            >
            <style
              id="label"
              borderColor="#4E4D4D"
              fontSize="16"
              fontWeight="normal"
              lineHeight="24"
              marginBottom="8"
            />
            </style>
            <style
              id="container"
              height="400"
              borderWidth="1"
              margin="20"
            >
            </style>
        </styles>
        <body style="Body">
          <header style="Header">
            <text action="back" href="#" style="Header__Back">Back</text>
            <text style="Header__Title">automaticallyAdjustContent</text>
          </header>
          <view style="container"  scroll="true">
              <view>
                <text style="label">Label</text>
                <text-field
                  placeholder="Edit your text"
                  placeholderTextColor="#8D9494"
                  name="text"
                  style="input"
                />
                </text-field>
              </view>
          </view>
        </body>
      </screen>
    </doc>

**Comment by adamstep** [comment]
@ashwinibm I think you were exploring integration with keyboard scroll views a while ago. Any ideas what might be going on here?

**Comment by Jasonwei1106** [comment]
Hi @adamstep, sorry, I'm not sure why this happened. But it was an issue on keyboardawarescrollview. So I used this alternative way to solve it.

**Comment by ashwinibm** [comment]
Hi @Jasonwei1106 
I tested your [fix PR](https://github.com/Instawork/hyperview/pull/303) but was still able to see the same issue you mentioned above intermittently.

Upon investigating further, the mark up you shared was a missing flex property on the body style. 
So you may update that to `<style id="Body" backgroundColor="white" flex="1" />` and try. It works fine.

https://user-images.githubusercontent.com/2883006/119644766-e25c1c00-be3a-11eb-951a-f3d683a66cee.mp4

**Comment by ashwinibm** [comment]
You can also check and play around with this [example](https://github.com/Instawork/hyperview/pull/308) for keyboard awareness in scrollable and non-scrollable views

**Comment by Jasonwei1106** [comment]
@ashwinibm The [example](https://github.com/Instawork/hyperview/pull/308) you mentioned still have the same issue if you scroll up. You will see the extra space if you pull the scrollview down. Here is how it looks if I remove my edition `props.automaticallyAdjustContentInsets = false;` and added `flex="1"` in the body

https://user-images.githubusercontent.com/37089057/119752278-4c260580-becf-11eb-8ebd-2d44debcee6c.mov

**Comment by ashwinibm** [comment]
OK I see the issue. The fix LGTM. Just had a minor comment.

**Comment by ashwinibm** [comment]
Fixed in https://github.com/Instawork/hyperview/pull/303
