### ISSUE TITLE
Deploying

### ISSUE THREAD

**Issue by keepexploring** [Instawork/hyperview#328]
Hi there,

Just getting familiar with hyperview for the first time - so a completely new at this, just wondering where the docs are on how to deploy to the app store/host the server? Looks a really great project and keen to use but just could not see how to deploy. Are you able to point me in the right direction? Thanks! Sorry I have missed something obvious!

**Comment by keepexploring** [comment]
So I see you would deploy the HTTP server to production, that is clear. But in terms of the app on the App Store, is there a standard app that just needs icons changing, name, server URL etc, which can then be simply deployed as a unique app to the App Store?

**Comment by adamstep** [comment]
Hi @keepexploring , sorry for the late reply. You are correct, you will need to deploy an HTTP server to product, which servs all of the XML for your app.

In terms of getting into the app store, a good place to start is with the Expo demo app in https://github.com/Instawork/hyperview/tree/master/demo. Expo provides guides for deploying the app, including customizations like the icon, splash screen, etc. You would also want to modify the entrypoint URL in the code here: https://github.com/Instawork/hyperview/blob/master/demo/navigation/AppNavigator.js#L43

Hope that helps, let me know if you have more questions!

**Comment by keepexploring** [comment]
Thanks so much for getting back to me. I had not clicked that it was using Expo, makes sense now. Thanks!
