### ISSUE TITLE
Question: How to deal with screen adaptation?

### ISSUE THREAD

**Issue by Mengsha97** [Instawork/hyperview#343]
Hi, as we all know, in most mobile app developments, we have to deal with the problem of screen adaptation. I would like to know if you have any solutions and ideas on screen adaptation for hyperview? I have scanned all the titles of issues, but did not find related issues, so I created a new issue, and want to discuss this with you. I hope you can give me some advice, thank you!

**Comment by adamstep** [comment]
Hi @Mengsha97 , there are a few ways to deal with different size screens on mobile devices:

- Hyperview uses Flexbox-based styling. So you can create UIs without defining absolute coordinates, in which case the UI can stretch or shrink to fill the available screen space.
- To handle mobile devices with a notch in the display, Hyperview supports [safe-area](https://hyperview.org/docs/reference_body#safe-area) attribute for styling
- If you need more control, you can send the dimensions of the screen in a request header to your backend. Then, on the server-side, you can use those dimensions to render a different UI to fit the screen.

Hope that helps!

**Comment by Mengsha97** [comment]
It is very helpful. I will try something according to the ideas you provided. Thank you so much!
