### ISSUE TITLE
Add support for alert buttons style

### ISSUE THREAD

**Issue by flochtililoch** [Instawork/hyperview#348]
[RN Alert API](https://reactnative.dev/docs/0.64/alert#buttons) allows configuring buttons on iOS to render according to OS-level style, i.e. "default", "cancel" or "destructive". 

Proposal: Add `style` property to `alert:option` element.

i.e.

```xml
  <behavior
    action="alert"
    alert:title="Do you want to delete this event?"
    trigger="press"
  >
    <alert:option
      action="cancel"
      alert:style="cancel"
      alert:label="Cancel"
    />
    <alert:option
      action="..."
      alert:style="destructive"
      alert:label="Delete"
    />
  </behavior>
```

**Comment by adamstep** [comment]
Here's the relevant HV behavior that interacts with the RN alert API: https://github.com/Instawork/hyperview/blob/master/src/behaviors/hv-alert/index.js#L85

- When generating the options, we can read the XML attribute for style and add it to the option data.
- we'd want to add an example to the demo app here: https://github.com/Instawork/hyperview/tree/master/examples/advanced_behaviors/alert
- Update the XML schema here: https://github.com/Instawork/hyperview/blob/master/schema/alert.xsd

**Comment by flochtililoch** [comment]
done in #579
