### ISSUE TITLE
Requirement: support custom input elements

### ISSUE THREAD

**Issue by terryatgithub** [Instawork/hyperview#355]
hi @adamstep & all, 
Long time no see, hope you're all going well.

We need to support some custom input fields like below. 
We found it hard to implement based on current conditions. 

---
#### What do we want to implement?
As you can see in the below picture, there are some input fields for money amount. 
when it's focused, need to show the primitive number: '1234567890.00', 
and when it's blurred, need to show the formatted number:  '1,234,567,890.00'. 
and when the length of the amount exceeds a certain length, need to show '11.11M' or '11.11B'.
(the field also needs to support i18n, where may show '1.234.567.890,00' in some country.)

![image](https://user-images.githubusercontent.com/12246394/136492750-684480ed-5e14-4ac8-8b4a-24510bd4502f.png)

---
#### Proposal
The method we think of is:
add a 'custom namespace logic' through an extension mechanism similar to behaviors.
https://github.com/Instawork/hyperview/blob/d09230293919911731238c1e36c985e1260a2131/src/index.js#L78
so we can add a custom RN input field component, and register it to our custom namespace. 
and with some changes in the below code, the customized elements can be submitted together.

https://github.com/Instawork/hyperview/blob/d09230293919911731238c1e36c985e1260a2131/src/services/index.js#L276
```javascript
  // TODO: It would be more flexible to grab any element with a name and value.
  FORM_NAMES
    // Get all inputs in the form
    .reduce((acc: Array<Element>, tag: LocalName) => {
      const inputElements: NodeList<Element> = formElement.getElementsByTagNameNS(
        Namespaces.HYPERVIEW, // <--- new customised namespace will be used here.
        tag,
      );
```
How do you think of this proposal, or is there a better way to support this feature?

Looking forward to your prompt response.
Regards.

**Comment by terryatgithub** [comment]
I've verified this solution initially, and now try to prepare a PR.

**Comment by terryatgithub** [comment]
hi @flochtililoch, could you please help with this issue? thank you.

**Comment by terryatgithub** [comment]
hi @adamstep , glad to see your reply, hope you are all going well.

Your attempt seems good. 
The logic of extracting the value is scattered into each input element, therefore it offers more flexibility.
But I didn't see where and how we can register such custom input elements. 
Looking forward to your implementation.

> I like your approach with registering namespaces. Perhaps it should be extended to be more precise. Instead of registering namespaces, we have a registry of input elements (namespace + element name). That way, we only serialized data from elements specifically identified as input elements.

thank you very much.

**Comment by adamstep** [comment]
Yes, the part that would change is `FORM_NAMES` which is currently hard-coded here: https://github.com/Instawork/hyperview/blob/d09230293919911731238c1e36c985e1260a2131/src/types.js#L47

Let me update my branch with a full implementation.

**Comment by adamstep** [comment]
I updated my branch with a more complete solution, @flochtililoch @terryatgithub let me know if this makes sense. Still needs to be thoroughly tested: https://github.com/Instawork/hyperview/compare/adam/form-values?expand=1

**Comment by adamstep** [comment]
@terryatgithub this PR is ready for review, please let me know if you have any comments: https://github.com/Instawork/hyperview/pull/359

I think it was best to keep the method simple and only return `Array<[string, string]>`. However, there is a helper function to extract the common attributes of `name` and `value`. Custom components can use this function instead of writing their own implementation.

**Comment by terryatgithub** [comment]
@adamstep wow awesome, this PR is just like a work of art.

**Comment by adamstep** [comment]
@terryatgithub this should be in as part of version v0.45.0. Please try it out when you have a chance!

**Comment by terryatgithub** [comment]
> @terryatgithub this should be in as part of version v0.45.0. Please try it out when you have a chance!

Glad to hear that, sincerely thanks for all your great work! Hope you are all going well.
