### ISSUE TITLE
Support sticky header for scroll view

### ISSUE THREAD

**Issue by palaparthi** [Instawork/hyperview#380]
React native supports [stickyHeaderIndices](https://reactnative.dev/docs/scrollview#stickyheaderindices) for scroll view.

When `<view scroll="true">` we can support multiple `<sticky-header target="..." />` as children where `target` attribute references the view we want to make sticky.

Example
```
        <view scroll="true">
          <sticky-header target="view-1" />
          <sticky-header target="view-3" />
          <view id="view-0">
            <text style="Text">Non Sticky</text>
          </view>
          <view id="view-1">
            <text style="Text">Sticky</text>
          </view>
          <view id="view-2">
            <text style="Text">Non Sticky</text>
          </view>
          <view id="view-3">
            <text style="Text">Sticky</text>
          </view>
        </view>
```

**Comment by palaparthi** [comment]
@flochtililoch @adamstep Any thoughts?

**Comment by flochtililoch** [comment]
My immediate thought on the markup: it might be cleaner if the views would declare themselves as "sticky". Internally, the scroll view could re-compute the `stickyHeaderIndices` array as more child views are loaded.

```
        <view scroll="true">
          <view id="view-0">
            <text style="Text">Non Sticky</text>
          </view>
          <view id="view-1" sticky="true">
            <text style="Text">Sticky</text>
          </view>
          <view id="view-2">
            <text style="Text">Non Sticky</text>
          </view>
          <view id="view-3" sticky="true">
            <text style="Text">Sticky</text>
          </view>
        </view>
```

**Comment by palaparthi** [comment]
@adamstep I tried that, for my usecase I don't think its ideal to use `<section-list>`.  If you look at the screenshot I want to make only the tabs part sticky. For this to make it work with `<section-list>` I would need to put the tabs in `<section-title>` and the content in contacts tab would be an `<item>` which again has a `<list>` of contacts. There is prob a way to refactor everything to make it work with `<section-list>`. But imo this solution will be cleaner.

@flochtililoch that makes sense, We can make it clear in the documentation that only direct children of `<view scroll="true">` can have ` sticky="true"`.

![Simulator Screen Shot - iPhone 11 - 2022-02-07 at 12 34 22](https://user-images.githubusercontent.com/28518512/152841446-cf3243c5-db0b-4c84-8008-191b2e62e7b5.png)

**Comment by flochtililoch** [comment]
Regarding the `<section-list>` sticky header behavior, it's enabled by default on iOS and disabled by default on Android. It does not look like we provide an explicit way to set/unset (via [`stickySectionHeadersEnabled`](https://reactnative.dev/docs/0.63/sectionlist#stickysectionheadersenabled)), we should probably expose this.

**Comment by adamstep** [comment]
> @adamstep I tried that, for my usecase I don't think its ideal to use `<section-list>`. If you look at the screenshot I want to make only the tabs part sticky.

@palaparthi from the screenshot, it's not clear to me: do the tabs scroll into view, or are they static (always anchored to the blue headers?)

**Comment by palaparthi** [comment]
@adamstep They scroll into the view and remain sticky once they reach the top.

Here's how it should look

https://user-images.githubusercontent.com/28518512/152858693-e6280ae9-12ff-4053-b70a-fe6fb3c4ebcd.mp4

**Comment by adamstep** [comment]
@palaparthi thanks for clarifying. I agree that the current version of `<section-list>` is not the best for your use case, given the need to show/hide the items that would appear in a section of the list.

I do think @flochtililoch's proposal is the nicer syntax, since we try to limit adding new tags to the core lib.

**Comment by flochtililoch** [comment]
> Here's how it should look

Something that's inconsistent in the video above, the "From your contacts" is a section header that should also remain sticky as the scroll occurs (until the next section)

**Comment by palaparthi** [comment]
@flochtililoch thanks for catching that, I think contacts are using `<list>` instead of `<section-list>`, will look into it.
