### ISSUE TITLE
list items within a section list affect the upper level of items.

### ISSUE THREAD

**Issue by osaborio** [Instawork/hyperview#472]
```
<section-list>
  <section>
    <section-title />
    <item key="">
      <list >
          <item key="">
              This item is also considered an item for upper level
          </item>
      </list>
    </item>
  </section>
</section-list>

```

**Comment by flochtililoch** [comment]
Interesting, it looks like we fixed that in the past, in #131

**Comment by adamstep** [comment]
@flochtililoch I believe we fixed it for `<list>`, but not `<section-list>`. Section list still finds all item elements by tag name:
https://github.com/Instawork/hyperview/blob/master/src/components/hv-section-list/index.js#L96

**Comment by flochtililoch** [comment]
That's confusing - the markup and screenshots in #131 do mention use of section-list, and there's a code change related to section list there. I believe we first faced the issue in the network screen, where we have a nested list of suggested contacts under the contacts list. Maybe the contact list was not using a section-list after all and the description of the PR wasn't accurate.
