### ISSUE TITLE
Q: Is it possible to add hyperview in an existing native app?

### ISSUE THREAD

**Issue by szuniverse** [Instawork/hyperview#63]
I cannot find any documentation how to add Hyperview to an existing native iOS/Android project. Is it possible at all? If yes, where can I find any documentation?

**Comment by adamstep** [comment]
Hyperview is built on top of React Native. So to use Hyperview in an existing native iOS/Android project, you would first need to integrate React Native, and then add Hyperview following our documentation. React Native docs provide a guide here: https://facebook.github.io/react-native/docs/integration-with-existing-apps

I personally have never tried to integrate RN into an existing native app, so I cannot vouch for how well it works.
