### ISSUE TITLE
Add gap, rowGap, columnGap styles?

### ISSUE THREAD

**Issue by mdwagner** [Instawork/hyperview#679]
https://reactnative.dev/docs/flexbox#row-gap-column-gap-and-gap

What is the likelihood of adding these?

**Comment by flochtililoch** [comment]
Hi @mdwagner, these seems reasonable to add, I'll take a look.

**Comment by flochtililoch** [comment]
This is now available in 0.70.0

**Comment by mdwagner** [comment]
Thank you! Just updated it and it works!
