### ISSUE TITLE
Is there a schema?

### ISSUE THREAD

**Issue by withinboredom** [Instawork/hyperview#694]
I was trying out hyperview today in Intellij IDE, and it prompted me to download the schema based on the namespace. However, there wasn't one available at `https://hyperview.org/hyperview`.

Is there one available to validate the XML in the IDE?

**Comment by adamstep** [comment]
Hi @withinboredom , yes there is a schema available here: https://hyperview.org/schema/core.xsd . It uses references to multiple files, so hopefully your IDE follows those links.

You can also find the schema in the repo: https://github.com/Instawork/hyperview/tree/master/schema

**Comment by withinboredom** [comment]
Ah, perfecto! I was able to point it to the schema files in the node_modules directory and it works like a charm!
