### ISSUE TITLE
Example app: Navigation to home doesn't work.

### ISSUE THREAD

**Issue by Invertisment** [Instawork/hyperview#775]
I'm on commit aeed0cdbc3904ee92dd1306dd20dfe8dc467d6e9.
I ran it on Android AVD.

When I open the example app and navigate to 
Navigation -> Navigate -> Navigate to home
Then nothing happens.

The other screen navigation works just fine.
I think this is the problem with how you manage the `react-navigation/stack` component. I tried to generating their routes for a different app that I was building and it wasn't easy to accomplish so I didn't want to use it in my apps. Maybe this is what's also causing the trouble. I think that their routing doesn't really work for generation.

**Comment by Invertisment** [comment]
I managed to make it work using some routing hack.

**Comment by adamstep** [comment]
Hi @Invertisment , can you share the hack you used? We are currently replacing the navigation system to fix this, @hgray-instawork you might be interested.

**Comment by hgray-instawork** [comment]
Thanks @Invertisment and @adamstep, I reviewed and this is still not functional with the new navigation changes. I have added it to the list of demo updates we will address in the near future.
