### ISSUE TITLE
Add a reload button to hyperview screens in dev mode

### ISSUE THREAD

**Issue by divyanshu013** [Instawork/hyperview#78]
While in dev mode, it's often required to make changes on the template on server side and reload the screen on mobile client.

True hot reloading might be tricky to handle for now; we can render an absolute positioned view which reloads the screen (probably using the `reload` `action` would just work)

**Comment by adamstep** [comment]
We discussed this at the last Hyperview meeting, it's a good idea.

FYI there's a feature on our backend, if you add `?dev_mode=true` to the request, it will render a reload button in the header of the screen that does the `reload` action.

**Comment by divyanshu013** [comment]
Closing since I don't have to work with hyperview anymore.
