### ISSUE TITLE
Repetitively triggering the same behavior with large delay leads to buggy behavior

### ISSUE THREAD

**Issue by divyanshu013** [Instawork/hyperview#84]
When triggering a behavior multiple times with a large delay (say 1000), the UI becomes inconsistent and leads to buggy behavior. Please check the attached screen-cast. This probably happens since the newer behaviors will be added to the event loop and executed after the second screen has loaded.

We should figure out a better way to handle such cases. Probably ignoring the triggers after the first one (not sure if there is a use case for handling all the triggers with delay):

![demo](https://user-images.githubusercontent.com/6682655/60647562-a17c4800-9e5b-11e9-9b27-ab553fa3a51c.gif)

**Comment by adamstep** [comment]
@divyanshu013 good call-out. We're tracking this in Asana as well, I think the solution is that behaviors should be "disabled" while processing so they can't trigger again. This is how Intercooler handles it. We should also add the ability to modify styles when an element is disabled (graying out a button for example).

**Comment by divyanshu013** [comment]
Sounds good, we should come up with some new spec for the disabled styles.

Could it be beneficial to provide an attribute for disabling/enabling the behavior while processing? Or it should be always disabled?

**Comment by divyanshu013** [comment]
Closing since I don't have to work with hyperview anymore.
