### ISSUE TITLE
TypeScript types do not seem to be published with the NPM package.

### ISSUE THREAD

**Issue by deej-io** [Instawork/hyperview#846]
I am looking to use hyperview for a new project and have checkout the demo app. I have immediately hit an an error when importing the library.

```
Diagnostics:
1. Could not find a declaration file for module 'hyperview'. '/home/djr/dev/scratch/hyperview/demo/node_modules/hyperview/lib/index.js' implicitly has an 'any' type.
     Try `npm i --save-dev @types/hyperview` if it exists or add a new declaration (.d.ts) file containing `declare module 'hyperview';` [7016]
```

I have noticed that there is no `TS` or `DT` on the NPM package: https://www.npmjs.com/package/hyperview and there is no corresponding @types/hyperview either.

It seems that the published package is just the compiled JavaScript, rather than the original TypeScript, so I think there could be something up with the publishing pipeline.

**Comment by adamstep** [comment]
@hgray-instawork is this something you can look into?

**Comment by hgray-instawork** [comment]
Will do, thanks for bringing it to our attention @deej-io

**Comment by hgray-instawork** [comment]
@deej-io , after looking over a few different options, we have decided that we no longer need to publish the transpiled version of the code. We have the src included in the library which has all of the Typescript files. We have updated our publish steps and our package.json to point to src/index.ts as the main entry point. This update will be included in our next release. I hope that will resolve the issue for you.

**Comment by hgray-instawork** [comment]
We have released this change in Hyperview 0.79.0. That should resolve your issue. Thanks again for letting us know.

**Comment by deej-io** [comment]
Ace! Thank you for sorting :)

I had been using the git HEAD with success once I saw you'd merged a fix and it's been great!

**Comment by hgray-instawork** [comment]
Great, let us know how everything else goes. We always love to hear about how our product is being used.
