### ISSUE TITLE
<modifier pressed="true"> not working in fresh app

### ISSUE THREAD

**Issue by fbinz** [Instawork/hyperview#893]
I'm banging my head against the wall trying to understand why the basic example for the pressed modifier is not working in our app. I've created a reproduction repository here: [Link](https://github.com/fbinz/hyperview-test)

It's just a fresh expo app, the hyperview is instantiated here: [Link](https://github.com/fbinz/hyperview-test/blob/main/my-app/app/(tabs)/index.tsx#L36).

The document that's served is the second example from the documentation on the <modifier> element: [Link](https://hyperview.org/docs/reference_modifier)

Any ideas what's going on?
Could it be a dependency issue? To get hyperview to install, I need to `--force` install, since some peer-dependencies are incompatible with the current expo dependencies.

Unfortunately I have to admit, that I've not been able to find the code that eventually applies the "pressed" styles. I've found some promising code in [hyper-ref](https://github.com/Instawork/hyperview/blob/master/src/core/hyper-ref/index.tsx), but alas this does not even get executed in my case. 

So any pointers on where I should look to debug this issue would also be highly appreciated. :)

**Comment by fbinz** [comment]
Ok, I now know what happened: The "pressed" modifier only seems to have an effect, when the corresponding element has a behavior attached. 
In hindsight, that makes sense, because only the "href" attribute actually makes an element pressable in the first place.

**Comment by adamstep** [comment]
I'm glad you figured it out @fbinz . Is there something that could be more clear in the docs to avoid the confusion?

**Comment by fbinz** [comment]
Hey @adamstep ,

I think the second example in the [documentation on modifiers](https://hyperview.org/docs/reference_modifier) might be misleading:

```<doc xmlns="https://hyperview.org/hyperview">
  <screen id="main">
    <styles>
      <style
        id="Button"
        backgroundColor="#EEE"
        padding="24"
      >
        <modifier pressed="true">
          <style backgroundColor="#AAA" />
        </modifier>
      </style>

      <style
        id="Button__Label"
        color="#000"
      >
        <modifier pressed="true">
          <style color="red" />
        </modifier>
      </style>
    </styles>
    <body>
      <view style="Button">
        <text style="Button__Label">Press me</text>
      </view>
    </body>
  </screen>
</doc>
```
That's the example I replicated in the reproduction repository, which also does not actually trigger the `pressed` styles, since the view does not have an `href` attribute.
So, just adding an example `href` (maybe even the hash-route `#` works?) and maybe a paragraph like the following would suffice:

```
Keep in mind that `pressed` styles will only have any effect when an element is actually pressable, that is, when the element has some kind of behavior attached to it via an `href` and other behavior attributes.
```
