### ISSUE TITLE
Demo instructions are outdated

### ISSUE THREAD

**Issue by ereOn** [Instawork/hyperview#996]
Hi,

I've been trying to follow the steps at: [Getting started](https://hyperview.org/docs/guide_installation) but haven't succeed in getting this to work.

If I follow blindly the instructions, I get this upon starting the iOS emulator:

<img width="255" alt="image" src="https://github.com/user-attachments/assets/814de835-a5ef-4c13-b348-8f098fcd28b2">

The guide mentions a `demo/src/constants.js` file but [none exists](https://github.com/Instawork/hyperview/tree/master/demo/src).

I could find something in `app.config.ts`:

<img width="482" alt="image" src="https://github.com/user-attachments/assets/2de4856f-6a44-49aa-8ec1-d53e76786227">

And if I change the port `8085` to `8081` things seem to move further and I get:

<img width="482" alt="image" src="https://github.com/user-attachments/assets/2c3e2664-208b-474b-8055-8d22e060bbb3">

When inspecting the request in the debug console I can see that it makes a request to a non-existent route:

<img width="516" alt="image" src="https://github.com/user-attachments/assets/2632f064-2da2-4df1-99fd-f9423873048a">

At this point, I have to say I am at loss at understanding the situation. I don't know `yarn` or `Expo` besides what I've quickly read on the topic, and I am not well versed enough in the NPM/front-end web ecosystem to even know where to continue.

What am I missing ? I've read the guide several times and it doesn't seem like I forget any steps there. My install is clean too.

Thanks!

**Comment by flochtililoch** [comment]
Closing for now as outdated content was updated in #997
